services:
    n2w:
        class: PHPViet\Symfony\NumberToWords\Service
        arguments: ['@service_container']
        public: true
    n2w_south_dictionary:
        class: PHPViet\NumberToWords\SouthDictionary
        public: true
    n2w_standard_dictionary:
        class: PHPViet\NumberToWords\Dictionary
        public: true
    n2w_twig_extension:
        class: PHPViet\Symfony\NumberToWords\Twig\Extension\N2WExtension
        arguments: ['@n2w']
        tags:
            - { name: twig.extension }
    PHPViet\NumberToWords\DictionaryInterface:
        class: PHPViet\NumberToWords\Dictionary
