services:
    n2w:
        class: PHPViet\Symfony\NumberToWords\Service
        arguments: ['@service_container']
        public: true
        shared: false
    n2w_south_dictionary:
        class: PHPViet\NumberToWords\SouthDictionary
        public: true
    n2w_standard_dictionary:
        class: PHPViet\NumberToWords\Dictionary
        public: true
    PHPViet\NumberToWords\DictionaryInterface: '@n2w_standard_dictionary'
